resilience4j:
  circuitbreaker:
    instances:
      identityService:
        slidingWindowSize: 10 # Check last 10 calls
        failureRateThreshold: 50 # Trip if 50% fail
        waitDurationInOpenState: 10000 # Wait 10s before trying again
management:
  health:
    circuit breakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics
spring:
  cache:
    type: redis
    data:
      redis:
        host: localhost
        port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5442/rideeasy_db
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver



  jpa:
    hibernate:
      ddl-auto: update # Automatically creates/updates tables based on your Java classes
    show-sql: true # Shows the actual SQL queries in your console (great for testing)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect