#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true # Automatically finds services in Eureka
#      routes:
#        - id: identity-route
#          uri: lb://SERVICE-IDENTITY # "lb://" tells it to use the Load Balancer
#          predicates:
#            - Path=/api/v1/auth/**
server:
  port: 8080 # This is the port your frontend will call

spring:
  application:
    name: infra-api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service-route
          uri: lb://SERVICE-IDENTITY # Uses Eureka to find your 3 instances
          predicates:
            - Path=/api/v1/identity/** # Any request starting with this...
          filters:
            - StripPrefix=1 # Removes '/api/v1/identity' before passing to service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/